version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Rahul5.7@postgres:5432/notification
      - RABBITMQ_BROKER=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A app.broker.celery_app worker -Q notifications --loglevel=info
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Rahul5.7@postgres:5432/notification
      - RABBITMQ_BROKER=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: Rahul5.7
      POSTGRES_DB: notification
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
